# Generated by Django 3.1.2 on 2023-05-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampleApp', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='publications',
            new_name='students',
        ),
    ]
